services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: djangomatic-nextjs-client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BASE_URL: http://127.0.0.1:8000
      # NEXT_PUBLIC_BASE_URL: https://djangomatic2.azurewebsites.net
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
