import type { Config } from "tailwindcss";

import { heroui } from "@heroui/theme";

/** @type {import("tailwindcss").Config} */
const config = {
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx,css}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontWeight: {
        normal: "400",
        bold: "700",
      },
      keyframes: {
        hide: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        slideIn: {
          from: {
            transform: "translateX(calc(100% + var(--viewport-padding)))",
          },
          to: { transform: "translateX(0)" },
        },
        slideDown: {
          from: { height: "0px" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        slideUp: {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0px" },
        },
        swipeOut: {
          from: { transform: "translateX(var(--radix-toast-swipe-end-x))" },
          to: { transform: "translateX(calc(100% + var(--viewport-padding)))" },
        },
      },
      animation: {
        hide: "hide 100ms ease-in",
        slideIn: "slideIn 150ms cubic-bezier(0.16, 1, 0.3, 1)",
        swipeOut: "swipeOut 100ms ease-out",
        slideDown: "slideDown 300ms cubic-bezier(0.87, 0, 0.13, 1)",
        slideUp: "slideUp 300ms cubic-bezier(0.87, 0, 0.13, 1)",
      },
      typography: () => ({
        // ({ theme }: { theme: any }) => ({
        lightTheme: {
          css: {
            "--tw-prose-body": "#003C7D",
            "--tw-prose-headings": "#003C7D",
            "--tw-prose-lead": "#096BDD",
            "--tw-prose-links": "#096BDD",
            "--tw-prose-bold": "#003C7D",
            "--tw-prose-counters": "#0053AD",
            "--tw-prose-bullets": "#2285F6",
            "--tw-prose-hr": "#51A0F9",
            "--tw-prose-quotes": "#003C7D",
            "--tw-prose-quote-borders": "#51A0F9",
            "--tw-prose-captions": "#096BDD",
            "--tw-prose-code": "#003C7D",
            "--tw-prose-pre-code": "#DEF2FF",
            "--tw-prose-pre-bg": "#096BDD",
            "--tw-prose-th-borders": "#51A0F9",
            "--tw-prose-td-borders": "#B0D6FF",
            "--tw-prose-invert-body": "#EDE9F6",
            "--tw-prose-invert-headings": "#EDE9F6",
            "--tw-prose-invert-lead": "#AB79F8",
            "--tw-prose-invert-links": "#AB79F8",
            "--tw-prose-invert-bold": "#EDE9F6",
            "--tw-prose-invert-counters": "#D19CFF",
            "--tw-prose-invert-bullets": "#E4AEFF",
            "--tw-prose-invert-hr": "#6D4AAA",
            "--tw-prose-invert-quotes": "#EDE9F6",
            "--tw-prose-invert-quote-borders": "#6D4AAA",
            "--tw-prose-invert-captions": "#AB79F8",
            "--tw-prose-invert-code": "#EDE9F6",
            "--tw-prose-invert-pre-code": "#2E1D4A",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "#6D4AAA",
            "--tw-prose-invert-td-borders": "#432C6A",
          },
        },
        darkTheme: {
          css: {
            "--tw-prose-body": "#AEDFFA",
            "--tw-prose-headings": "#AEDFFA",
            "--tw-prose-lead": "#31FEF6",
            "--tw-prose-links": "#31FEF6",
            "--tw-prose-bold": "#AEDFFA",
            "--tw-prose-counters": "#23E5DD",
            "--tw-prose-bullets": "#52FFF8",
            "--tw-prose-hr": "#096BDD",
            "--tw-prose-quotes": "#AEDFFA",
            "--tw-prose-quote-borders": "#096BDD",
            "--tw-prose-captions": "#31FEF6",
            "--tw-prose-code": "#AEDFFA",
            "--tw-prose-pre-code": "#002244",
            "--tw-prose-pre-bg": "#31FEF6",
            "--tw-prose-th-borders": "#096BDD",
            "--tw-prose-td-borders": "#0053AD",
            "--tw-prose-invert-body": "#003C7D",
            "--tw-prose-invert-headings": "#003C7D",
            "--tw-prose-invert-lead": "#096BDD",
            "--tw-prose-invert-links": "#096BDD",
            "--tw-prose-invert-bold": "#003C7D",
            "--tw-prose-invert-counters": "#0053AD",
            "--tw-prose-invert-bullets": "#2285F6",
            "--tw-prose-invert-hr": "#51A0F9",
            "--tw-prose-invert-quotes": "#003C7D",
            "--tw-prose-invert-quote-borders": "#51A0F9",
            "--tw-prose-invert-captions": "#096BDD",
            "--tw-prose-invert-code": "#003C7D",
            "--tw-prose-invert-pre-code": "#DEF2FF",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "#51A0F9",
            "--tw-prose-invert-td-borders": "#B0D6FF",
          },
        },
      }),
    },
  },
  variants: {
    extend: {
      fontStyle: ["responsive", "hover", "focus", "active"],
      fontWeight: ["responsive", "hover", "focus", "active"],
    },
  },
  darkMode: "class",
  safelist: [
    {
      pattern:
      /(bg|border|text)-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose|primary|secondary|success|warning|danger)-(100|200|300|400|500|600|700|800|900|950)/,
      variants: ["hover", "focus", "active"],
    },
  ],
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    heroui({
      themes: {
        light: {
          colors: {
            background: "#CAE0E5",
            foreground: "#003C7D",
            primary: {
              50: "#E3F2FD",
              100: "#BBDEFB",
              200: "#90CAF9",
              300: "#64B5F6",
              400: "#42A5F5",
              500: "#2196F3",
              600: "#1E88E5",
              700: "#1976D2",
              800: "#1565C0",
              900: "#0D47A1",
              foreground: "#FFFFFF",
              DEFAULT: "#2196F3",
            },
            secondary: {
              50: "#F3E8FF",
              100: "#E0BBFF",
              200: "#CC8EFF",
              300: "#B861FF",
              400: "#A434FF",
              500: "#8F00FF",
              600: "#7200CC",
              700: "#560099",
              800: "#3A0066",
              900: "#1D0033",
              foreground: "#FFFFFF",
              DEFAULT: "#A434FF",
            },
            success: {
              50: "#E8F5E9",
              100: "#C8E6C9",
              200: "#A5D6A7",
              300: "#81C784",
              400: "#66BB6A",
              500: "#4CAF50",
              600: "#43A047",
              700: "#388E3C",
              800: "#2E7D32",
              900: "#1B5E20",
              foreground: "#FFFFFF",
              DEFAULT: "#4CAF50",
            },
            warning: {
              50: "#FFFDE7",
              100: "#FFF9C4",
              200: "#FFF59D",
              300: "#FFF176",
              400: "#FFEE58",
              500: "#FFEB3B",
              600: "#FDD835",
              700: "#FBC02D",
              800: "#F9A825",
              900: "#F57F17",
              foreground: "#FFFFFF",
              DEFAULT: "#FFEB3B",
            },
            danger: {
              50: "#FFEBEE",
              100: "#FFCDD2",
              200: "#EF9A9A",
              300: "#E57373",
              400: "#EF5350",
              500: "#F44336",
              600: "#E53935",
              700: "#D32F2F",
              800: "#C62828",
              900: "#B71C1C",
              foreground: "#FFFFFF",
              DEFAULT: "#F44336",
            },
          },
        },
        dark: {
          colors: {
            background: "#02181D",
            foreground: "#AEDFFA",
            primary: {
              50: "#002244",
              100: "#003C7D",
              200: "#0053AD",
              300: "#096BDD",
              400: "#2285F6",
              500: "#51A0F9",
              600: "#81BBFD",
              700: "#B0D6FF",
              800: "#DEF2FF",
              900: "#EFF8FF",
              foreground: "#021F26",
              DEFAULT: "#2285F6",
            },
            secondary: {
              50: "#1D0033",
              100: "#3A0066",
              200: "#560099",
              300: "#7200CC",
              400: "#8F00FF",
              500: "#A434FF",
              600: "#B861FF",
              700: "#CC8EFF",
              800: "#E0BBFF",
              900: "#F3E8FF",
              foreground: "#021F26",
              DEFAULT: "#8F00FF",
            },
            success: {
              50: "#0A1700",
              100: "#284303",
              200: "#45700B",
              300: "#619D13",
              400: "#7EBB1B",
              500: "#9AD923",
              600: "#B7F72B",
              700: "#D3FF33",
              800: "#EFFF3B",
              900: "#FFFF43",
              foreground: "#021F26",
              DEFAULT: "#9AD923",
            },
            warning: {
              50: "#332B00",
              100: "#665600",
              200: "#998000",
              300: "#CCAA00",
              400: "#FFCC00",
              500: "#FFD700",
              600: "#FFE033",
              700: "#FFEA66",
              800: "#FFF399",
              900: "#FFFDCC",
              foreground: "#021F26",
              DEFAULT: "#FFD700",
            },
            danger: {
              50: "#330000",
              100: "#660000",
              200: "#990000",
              300: "#CC0000",
              400: "#FF0000",
              500: "#FF3333",
              600: "#FF6666",
              700: "#FF9999",
              800: "#FFCCCC",
              900: "#FFFFFF",
              foreground: "#021F26",
              DEFAULT: "#FF3333",
            },
          },
        },
      },
    }),
  ],
} satisfies Config;

export default config;
