import { FiscalMonths, GainTrackingStatus } from "@prisma/client";

import { GainsTrackingRecordItem } from "@/src/interfaces/rnd";

// Generate mock GainsTrackingRecordItem data that matches the Prisma model
export const mockGainsRecords: GainsTrackingRecordItem[] = [
  {
    id: "1",
    createdAt: new Date("2025-05-10"),
    taskId: "task-1",
    name: "Invoice Processing Automation",
    region: "North America",
    hasGains: true,
    replaceOffshore: false,
    timeInitial: 40,
    timeSaved: 25,
    status: GainTrackingStatus.OPEN,
    monthlyCosts: [
      {
        id: "mc-1-1",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.June,
        cost: 5100,
      },
      {
        id: "mc-1-2",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.December,
        cost: 5200,
      },
      {
        id: "mc-1-3",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.January,
        cost: 4800,
      },
      {
        id: "mc-1-4",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.February,
        cost: 5300,
      },
      {
        id: "mc-1-5",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.March,
        cost: 4900,
      },
      {
        id: "mc-1-6",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.April,
        cost: 5100,
      },
      {
        id: "mc-1-7",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.March,
        cost: 5000,
      },
    ],
    comments: "Successfully automated invoice processing workflow",
  },
  {
    id: "2",
    createdAt: new Date("2025-08-15"),
    taskId: "task-2",
    name: "Customer Support Chatbot",
    region: "Global",
    hasGains: true,
    replaceOffshore: true,
    timeInitial: 60,
    timeSaved: 40,
    status: GainTrackingStatus.CLOSED,
    monthlyCosts: [
      {
        id: "mc-2-1",
        gainsRecordId: "2",
        fiscalYear: 2025,
        month: FiscalMonths.August,
        cost: 8500,
      },
      {
        id: "mc-2-2",
        gainsRecordId: "2",
        fiscalYear: 2025,
        month: FiscalMonths.September,
        cost: 8300,
      },
      {
        id: "mc-2-3",
        gainsRecordId: "2",
        fiscalYear: 2025,
        month: FiscalMonths.October,
        cost: 8700,
      },
      {
        id: "mc-2-4",
        gainsRecordId: "2",
        fiscalYear: 2025,
        month: FiscalMonths.November,
        cost: 8600,
      },
      {
        id: "mc-2-5",
        gainsRecordId: "2",
        fiscalYear: 2025,
        month: FiscalMonths.July,
        cost: 8400,
      },
    ],
  },
  {
    id: "3",
    createdAt: new Date("2024-10-01"),
    taskId: "task-3",
    name: "HR Onboarding System",
    region: "Europe",
    hasGains: true,
    replaceOffshore: false,
    timeInitial: 25,
    timeSaved: 15,
    status: GainTrackingStatus.OPEN,
    monthlyCosts: [
      {
        id: "mc-3-1",
        gainsRecordId: "3",
        fiscalYear: 2024,
        month: FiscalMonths.October,
        cost: 3200,
      },
      {
        id: "mc-3-2",
        gainsRecordId: "3",
        fiscalYear: 2024,
        month: FiscalMonths.November,
        cost: 3100,
      },
      {
        id: "mc-3-3",
        gainsRecordId: "3",
        fiscalYear: 2024,
        month: FiscalMonths.September,
        cost: 3300,
      },
      {
        id: "mc-3-4",
        gainsRecordId: "4",
        fiscalYear: 2024,
        month: FiscalMonths.July,
        cost: 3000,
      },
    ],
  },
  {
    id: "4",
    createdAt: new Date("2024-01-05"),
    taskId: "task-4",
    name: "Inventory Management System",
    region: "APAC",
    hasGains: true,
    replaceOffshore: true,
    timeInitial: 45,
    timeSaved: 30,
    status: GainTrackingStatus.OPEN,
    monthlyCosts: [
      {
        id: "mc-4-1",
        gainsRecordId: "4",
        fiscalYear: 2024,
        month: FiscalMonths.January,
        cost: 12000,
      },
      {
        id: "mc-4-2",
        gainsRecordId: "4",
        fiscalYear: 2024,
        month: FiscalMonths.February,
        cost: 11800,
      },
      {
        id: "mc-4-3",
        gainsRecordId: "4",
        fiscalYear: 2024,
        month: FiscalMonths.March,
        cost: 12200,
      },
    ],
  },
  {
    id: "5",
    createdAt: new Date("2025-03-18"),
    taskId: "task-5",
    name: "Gains board",
    region: "Atlantic",
    hasGains: true,
    replaceOffshore: true,
    timeInitial: 140,
    timeSaved: 25,
    status: GainTrackingStatus.OPEN,
    monthlyCosts: [
      {
        id: "mc-3-1",
        gainsRecordId: "3",
        fiscalYear: 2024,
        month: FiscalMonths.December,
        cost: 3200,
      },
      {
        id: "mc-1-1",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.January,
        cost: 5100,
      },
      {
        id: "mc-1-2",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.February,
        cost: 5200,
      },
      {
        id: "mc-1-3",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.March,
        cost: 4800,
      },
      {
        id: "mc-1-4",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.April,
        cost: 5300,
      },
      {
        id: "mc-1-5",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.May,
        cost: 4900,
      },
      {
        id: "mc-1-6",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.June,
        cost: 5100,
      },
      {
        id: "mc-1-7",
        gainsRecordId: "1",
        fiscalYear: 2025,
        month: FiscalMonths.July,
        cost: 5000,
      },
      {
        id: "mc-2-17",
        gainsRecordId: "2",
        fiscalYear: 2025,
        month: FiscalMonths.August,
        cost: 8500,
      },
      {
        id: "mc-4-1",
        gainsRecordId: "4",
        fiscalYear: 2024,
        month: FiscalMonths.September,
        cost: 12000,
      },
      {
        id: "mc-4-2",
        gainsRecordId: "4",
        fiscalYear: 2024,
        month: FiscalMonths.October,
        cost: 11800,
      },
      {
        id: "mc-4-3",
        gainsRecordId: "4",
        fiscalYear: 2024,
        month: FiscalMonths.November,
        cost: 12200,
      },
    ],
    comments: "Successfully automated invoice processing workflow",
  },
];
