export type SaasData = typeof saasData;

export const saasData = {
  tds_saas: [
    // Address Breakdown --> not yet implemented
    {
      label: "UNAV - Address Breakdown",
      type: "hld",
      href: "/saas/tds/hld/spkv_adr_xls",
      endpoint: "/saas/tds/",
      desc: "address_breakdown",
      version: "0.1.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "N",
    },
    // DFN Boundaries --> not yet implemented
    {
      label: "UNAV - DFN Boundaries",
      type: "hld",
      href: "/saas/tds/hld/spkv_dfn_lots",
      endpoint: "/saas/tds/",
      desc: "dfn_boundaries",
      version: "0.1.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "N",
    },
    // GPS to SHP --> not yet implemented
    {
      label: "UNAV - GPS to SHP",
      type: "hld",
      href: "/saas/tds/hld/spkv_gps_shp",
      endpoint: "/saas/tds/",
      desc: "gps_to_shp",
      version: "0.1.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "N",
    },
    // GPS to Postgres
    {
      label: "GPS to Postgres",
      type: "hld",
      href: "/saas/tds/hld/spkv_gps_db",
      endpoint: "/saas/tds/ajax/query-import-gps-to-postgres/",
      desc: "gps_to_postgres",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // GPS Postgres - Override
    {
      label: "GPS to Postgres",
      type: "override",
      href: "/saas/tds/override/spkv_override_gps",
      endpoint: "/saas/tds/ajax/query-import-gps-to-postgres/",
      desc: "gps_to_postgres_refresh",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: true,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // HLD to KMZ --> not yet implemented
    {
      label: "UNAV - HLD to KMZ",
      type: "hld",
      href: "/saas/tds/hld/spkv_hld_kmz",
      endpoint: "/saas/tds/",
      desc: "hld_to_kmz",
      version: "0.1.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "N",
    },
    // HLD to Postgres
    {
      label: "HLD to Postgres",
      type: "hld",
      href: "/saas/tds/hld/spkv_hld_db",
      endpoint: "/saas/tds/ajax/query-import-hld-to-postgres/",
      desc: "hld_to_postgres",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // HLD Postgres - Override
    {
      label: "HLD to Postgres",
      type: "override",
      href: "/saas/tds/override/spkv_override_hld_db",
      endpoint: "/saas/tds/ajax/query-import-hld-to-postgres/",
      desc: "hld_to_postgres_refresh",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: true,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Node Quantities - admin
    {
      label: "Node Quantities",
      type: "admin",
      href: "/saas/tds/admin/spkv_node_qty",
      endpoint: "/saas/tds/ajax/query-extract-node-length-qt/",
      desc: "node_quantities",
      version: "1.0.0",
      date_upd: "2024-04-05",
      doc_href: "/saas/tds/empty",
      asDownloadable: true,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // HP by Splits1 - admin
    {
      label: "HP by Splits1",
      type: "admin",
      href: "/saas/tds/admin/spkv_hp_by_split1",
      endpoint: "/saas/tds/ajax/query-compile-hp-by-splits1/",
      desc: "hp_by_splits1",
      version: "1.0.2",
      date_upd: "2024-05-23",
      doc_href: "/saas/tds/empty",
      asDownloadable: true,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Poles automatic ID generator in DFN
    {
      label: "Poles Numbering",
      type: "lld",
      href: "/saas/tds/lld/poles_numbering",
      endpoint: "/saas/tds/ajax/query-poles-auto-id/",
      desc: "poles_numbering",
      version: "1.1.5",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/doc_pole_numbering",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Midspans calculation in DFN
    {
      label: "Midspan Calculation",
      type: "lld",
      href: "/saas/tds/lld/midspan_auto_calc",
      endpoint: "/saas/tds/ajax/query-midspan-auto-calc/",
      desc: "midspan_calculation",
      version: "1.3.4",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/doc_midspan_calculator",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Poles table pre-fill and suggestions calculation - by DFN
    {
      label: "DFN Poles Calculations",
      type: "lld",
      href: "/saas/tds/lld/dfn_poles_calc",
      endpoint: "/saas/tds/ajax/query-poles-dfn-calc/",
      desc: "dfn_poles_calculations",
      version: "1.3.3",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/doc_dfn_poles_calculator",
      asDownloadable: false,
      willOverride: false, // using willOverride to provide 'projectType' in API endpoint - will set to LLD
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Poles table pre-fill and suggestions calculation - by Node
    {
      label: "Node Poles Calculations",
      type: "hld",
      href: "/saas/tds/hld/node_poles_calc",
      endpoint: "/saas/tds/ajax/query-poles-dfn-calc/",
      desc: "node_poles_calculations",
      version: "1.3.2",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/doc_dfn_poles_calculator",
      asDownloadable: false,
      willOverride: true, // using willOverride to provide 'projectType' in API endpoint - will set to HLD
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Pole estimator for missing classes en lengths, by DFN
    {
      label: "Pole Class-Length Estimator",
      type: "lld",
      href: "/saas/tds/lld/pole_class_length_est",
      endpoint: "/saas/tds/ajax/query-pole-class-length-est/",
      desc: "pole_class_length_estimator",
      version: "1.1.5",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/doc_pole_class_length_estimator",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Extract Pole and HP data for DP
    {
      label: "Extract Data DP",
      type: "lld",
      href: "/saas/tds/lld/extract_data_dp",
      endpoint: "/saas/tds/ajax/query-extract-data-dp/",
      desc: "extract_data_dp",
      version: "1.1.3",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: true,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // ARCGIS API APPS
    // Import to DB621
    {
      label: "Import to DB621",
      type: "arcgis",
      href: "/saas/tds/arcgis/arcgis_api_import_db621",
      endpoint: "/saas/tds/ajax/arcgis/import-dfn-db621/",
      desc: "import_to_db621",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Update to DB621
    {
      label: "Update DB621",
      type: "arcgis",
      href: "/saas/tds/arcgis/arcgis_api_update_db621",
      endpoint: "/saas/tds/ajax/arcgis/update-dfn-db621/",
      desc: "update_db621",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spkv_snapshot",
      is_active: "Y",
    },
    // Snapshots from DB621
    {
      label: "Snapshots from DB621",
      type: "arcgis",
      href: "/saas/tds/arcgis/arcgis_api_snapshots_db621",
      endpoint: "/saas/tds/ajax/arcgis/auto-snapshots-db621/",
      desc: "snapshots_from_db621",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // DFN Bounds CRUD DB621
    {
      label: "DFN Bounds DB621",
      type: "arcgis",
      href: "/saas/tds/arcgis/arcgis_api_dfn_bounds_crud_db621",
      endpoint: "/saas/tds/ajax/arcgis/auto-dfn-crud-db621/",
      desc: "dfn_bounds_db621",
      version: "1.0.0",
      date_upd: "2024-04-22",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // SUPER APPS
    // Resolve Null Geom
    {
      label: "Resolve Null Geom - To-Do",
      type: "super",
      href: "/saas/tds/super/resolve_null_geom",
      endpoint: "/saas/tds/ajax/super/query-resolve-null-geom-main/",
      desc: "resolve_null_geom",
      version: "1.1.2",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Recover deleted data
    {
      label: "Recover from Version - To-Do",
      type: "super",
      href: "/saas/tds/super/recover_version",
      endpoint: "/saas/tds/ajax/super/query-recover-version-prod/",
      desc: "recover_from_version",
      version: "1.1.2",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Change Table Ownership UNIQ
    {
      label: "Change Table Ownership UNIQ - To-Do",
      type: "super",
      href: "/saas/tds/super/uniq_change_tbl_own",
      endpoint: "/saas/tds/ajax/super/query-change-ownership-uniq/",
      desc: "change_table_ownership_uniq",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Clean Table Ownership
    {
      label: "Clean Table Ownership - To-Do",
      type: "super",
      href: "/saas/tds/super/clean_tbl_own",
      endpoint: "/saas/tds/ajax/super/query-clean-table-ownership/",
      desc: "clean_table_ownership",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
    // Postgres Versioning
    {
      label: "Postgres Versioning - To-Do",
      type: "super",
      href: "/saas/tds/super/postgres_version",
      endpoint: "/saas/tds/ajax/super/query-postgres-version/",
      desc: "postgres_versioning",
      version: "1.0.1",
      date_upd: "2024-03-26",
      doc_href: "/saas/tds/empty",
      asDownloadable: false,
      willOverride: false,
      dbClass: "db_class_spokane_valley",
      is_active: "Y",
    },
  ],
  cogeco_saas: [
    // Format SHP data for TQC
    {
      label: "TQC SHP Format",
      type: "hld",
      href: "/saas/cogeco/hld/tqc_shp_format",
      desc_en: "Format SHP data extract from AutoCAD for TQC.",
      desc_fr: "Format fichiers SHP extraits d'AutoCAD pour TQC.",
      version: "1.1.3",
      date_upd: "2023-12-13",
      desc_upd_en: "Automatic rename for POTEAUX 'proprietai' field.",
      desc_upd_fr:
        "Renomatique automatique du champ 'proprietai' pour POTEAUX.",
      doc_href: "empty",
      is_active: "Y",
    },
  ],
  vistabeam_saas: [
    // GPS to SHP
    {
      label: "GPS to SHP",
      type: "hld",
      href: "/saas/vistabeam/hld/gps_shp",
      desc_en:
        "Compile and sanitize ungraded GPS survey as SHP suitable for HLD.",
      desc_fr:
        "Compile et nettoie relevé GPS non calibré, en SHP utilisable pour HLD.",
      version: "1.0.0",
      date_upd: "2024-01-23",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "N",
    },
    // GPS to Postgres
    {
      label: "GPS to Postgres",
      type: "hld",
      href: "/saas/vistabeam/hld/gps_db",
      desc_en: "Import new graded GPS survey, or append to existing tables.",
      desc_fr: "Importe nouveau relevé GPS calibré, ou ajoute à existant.",
      version: "1.0.0",
      date_upd: "2024-01-25",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "Y",
    },
    // GPS Postgres - Override
    {
      label: "GPS to Postgres",
      type: "override",
      href: "/saas/vistabeam/override/gps_db",
      desc_en: "Fresh GPS import, erasing old data.",
      desc_fr: "Nouvel import GPS, effaçant anciennes données.",
      version: "1.0.0",
      date_upd: "2024-01-25",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "Y",
    },
    // Poles table pre-fill and suggestions calculation - by Node
    {
      label: "Node Poles Calculations",
      type: "hld",
      href: "/saas/vistabeam/hld/node_poles_calc",
      desc_en: "Poles attachment suggestions and table pre-fill, by Node.",
      desc_fr:
        "Suggestions hauteurs d'attaches poteaux, et pre-remplissage tableaux, par noeud.",
      version: "1.0.0",
      date_upd: "2024-01-23",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "doc_dfn_poles_calculator",
      is_active: "Y",
    },
    // SUPER APPS
    // Resolve Null Geom
    {
      label: "Resolve Null Geom",
      type: "super",
      href: "/saas/vistabeam/super/resolve_null_geom",
      desc_en: "Postgres db remove Null geometries.",
      desc_fr: "Postgres db supprime les géometries Null.",
      version: "1.0.0",
      date_upd: "2024-01-23",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "Y",
    },
    // Recover deleted data
    {
      label: "Recover from Version",
      type: "super",
      href: "/saas/vistabeam/super/recover_version",
      desc_en: "Postgres db recover deleted data, from versioning.",
      desc_fr: "Postgres db restaure data supprimées, depuis versioning.",
      version: "1.0.0",
      date_upd: "2024-01-23",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "Y",
    },
  ],
  xplore_saas: [
    // Extract BOM summary from zip input
    {
      label: "Extract BOM Summary",
      type: "admin",
      href: "/saas/xplore/admin/extract_bom_summary",
      desc_en: "Extract BOM summary from zip input.",
      desc_fr: "Extraire un résumé BOM à partir d'un zip.",
      version: "1.0.0",
      date_upd: "2024-08-01",
      desc_upd_en: "First time release.",
      desc_upd_fr: "Première publication.",
      doc_href: "empty",
      is_active: "Y",
    },
  ],
};
