export type SaasData = typeof saasData;

export const saasData = {
  tds_saas: [
    // Address Breakdown
    {
      label: "Address Breakdown",
      type: "hld",
      href: "/saas/tds/spkv_adr_xls",
      desc: "Compile address breakdown as Excel file + Map screenshot.",
      version: "0.1.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "N",
    },
    // DFN Boundaries
    {
      label: "DFN Boundaries",
      type: "hld",
      href: "/saas/tds/spkv_dfn_lots",
      desc: "Generate AGOL DFN boundaries layer in Postgres, for client import.",
      version: "0.1.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "N",
    },
    // GPS to SHP
    {
      label: "GPS to SHP",
      type: "hld",
      href: "/saas/tds/spkv_gps_shp",
      desc: "Compile and sanitize ungraded GPS survey as SHP suitable for HLD.",
      version: "0.1.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "N",
    },
    // GPS to Postgres
    {
      label: "GPS to Postgres",
      type: "hld",
      href: "/saas/tds/spkv_gps_db",
      desc: "Import new graded GPS survey, or append to existing tables.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // GPS Postgres - Override
    {
      label: "GPS to Postgres",
      type: "override",
      href: "/saas/tds/spkv_override_gps",
      desc: "Fresh GPS import, erasing old data.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // HLD to KMZ
    {
      label: "HLD to KMZ",
      type: "hld",
      href: "/saas/tds/spkv_hld_kmz",
      desc: "Produce KMZ mapping for each DFN's HLD.",
      version: "0.1.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "N",
    },
    // HLD to Postgres
    {
      label: "HLD to Postgres",
      type: "hld",
      href: "/saas/tds/spkv_hld_db",
      desc: "Import new HLD, or append to existing tables.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // HLD Postgres - Override
    {
      label: "HLD to Postgres",
      type: "override",
      href: "/saas/tds/spkv_override_hld_db",
      desc: "Fresh HLD import, erasing old data.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // Node Quantities - admin
    {
      label: "Node Quantities",
      type: "admin",
      href: "/saas/tds/spkv_node_qty",
      desc: "Extract node AER/UG length quantities (ft).",
      version: "1.0.0",
      date_upd: "2024-04-05",
      desc_upd: "First time app deployment.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // HP by Splits1 - admin
    {
      label: "HP by Splits1",
      type: "admin",
      href: "/saas/tds/spkv_hp_by_split1",
      desc: "Compile HP by L1 splitters, inside a node.",
      version: "1.0.2",
      date_upd: "2024-05-23",
      desc_upd: "Resolve an issue when addresses are empty.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // Poles automatic ID generator in DFN
    {
      label: "Poles Numbering",
      type: "lld",
      href: "/saas/tds/poles_numbering",
      desc: "Create pole ID field based on the leaflet order.",
      version: "1.1.5",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/doc_pole_numbering",
      is_active: "Y",
    },
    // Midspans calculation in DFN
    {
      label: "Midspan Calculation",
      type: "lld",
      href: "/saas/tds/midspan_auto_calc",
      desc: "Recalculate a project midspans based on poles updates.",
      version: "1.3.4",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/doc_midspan_calculator",
      is_active: "Y",
    },
    // Poles table pre-fill and suggestions calculation - by DFN
    {
      label: "DFN Poles Calculations",
      type: "lld",
      href: "/saas/tds/dfn_poles_calc",
      desc: "Poles attachment suggestions and table pre-fill, by DFN.",
      version: "1.3.3",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/doc_dfn_poles_calculator",
      is_active: "Y",
    },
    // Poles table pre-fill and suggestions calculation - by Node
    {
      label: "Node Poles Calculations",
      type: "hld",
      href: "/saas/tds/node_poles_calc",
      desc: "Poles attachment suggestions and table pre-fill, by Node.",
      version: "1.3.2",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/doc_dfn_poles_calculator",
      is_active: "Y",
    },
    // Pole estimator for missing classes en lengths, by DFN
    {
      label: "Pole Class-Length Estimator",
      type: "lld",
      href: "/saas/tds/pole_class_length_est",
      desc: "Pole estimator for missing classes en lengths, by DFN.",
      version: "1.1.5",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/doc_pole_class_length_estimator",
      is_active: "Y",
    },
    // Extract Pole and HP data for DP
    {
      label: "Extract Data DP",
      type: "lld",
      href: "/saas/tds/extract_data_dp",
      desc: "Poles owners and HP data counts extractions, for DP.",
      version: "1.1.3",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // ARCGIS API APPS
    // Import to DB621
    {
      label: "Import to DB621",
      type: "arcgis",
      href: "/saas/tds/arcgis_api_import_db621",
      desc: "Import DFN design to DB621 & Auto Snapshots",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // Update to DB621
    {
      label: "Update DB621",
      type: "arcgis",
      href: "/saas/tds/arcgis_api_update_db621",
      desc: "Update DFN attributes to DB621.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // Snapshots from DB621
    {
      label: "Snapshots from DB621",
      type: "arcgis",
      href: "/saas/tds/arcgis_api_snapshots_db621",
      desc: "Snapshots only, from DB621.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // DFN Bounds CRUD DB621
    {
      label: "DFN Bounds DB621",
      type: "arcgis",
      href: "/saas/tds/arcgis_api_dfn_bounds_crud_db621",
      desc: "Import, update or delete DFN boundaries.",
      version: "1.0.0",
      date_upd: "2024-04-22",
      desc_upd: "First time app deployment.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // SUPER APPS
    // Resolve Null Geom
    {
      label: "Resolve Null Geom",
      type: "super",
      href: "/saas/tds/super_resolve_null_geom",
      desc: "Postgres db <b>Main</b><br>Remove Null geometries.",
      version: "1.1.2",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // Recover deleted data
    {
      label: "Recover from Version",
      type: "super",
      href: "/saas/tds/super_recover_version",
      desc: "Postgres db <b>Prod</b><br>Recover deleted data, from versioning.",
      version: "1.1.2",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // Change Table Ownership UNIQ
    {
      label: "Change Table Ownership UNIQ",
      type: "super",
      href: "/saas/tds/super_uniq_change_tbl_own",
      desc: "Postgres db <b>Prod</b><br><u>Change</u> table ownership and permissions from/to UNIQ.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // Clean Table Ownership
    {
      label: "Clean Table Ownership",
      type: "super",
      href: "/saas/tds/super_clean_tbl_own",
      desc: "Postgres db <b>Prod</b><br><u>Clean</u> table ownership and permissions in entire schema.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
    // Postgres Versioning
    {
      label: "Postgres Versioning",
      type: "super",
      href: "/saas/tds/super_postgres_version",
      desc: "Postgres versioning for untracked schemas and tables.",
      version: "1.0.1",
      date_upd: "2024-03-26",
      desc_upd: "French translation support and compatibility.",
      doc_href: "/saas/tds/empty",
      is_active: "Y",
    },
  ],
  cogeco_saas: [
    // Format SHP data for TQC
    {
      label: "TQC SHP Format",
      type: "cogeco",
      href: "/saas/cogeco/tqc_shp_format",
      desc_en: "Format SHP data extract from AutoCAD for TQC.",
      desc_fr: "Format fichiers SHP extraits d'AutoCAD pour TQC.",
      version: "1.1.3",
      date_upd: "2023-12-13",
      desc_upd_en: "Automatic rename for POTEAUX 'proprietai' field.",
      desc_upd_fr:
        "Renomatique automatique du champ 'proprietai' pour POTEAUX.",
      doc_href: "empty",
      is_active: "Y",
    },
  ],
  vistabeam_saas: [
    // GPS to SHP
    {
      label: "GPS to SHP",
      type: "hld",
      href: "/saas/vistabeam/gps_shp",
      desc_en:
        "Compile and sanitize ungraded GPS survey as SHP suitable for HLD.",
      desc_fr:
        "Compile et nettoie relevé GPS non calibré, en SHP utilisable pour HLD.",
      version: "1.0.0",
      date_upd: "2024-01-23",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "N",
    },
    // GPS to Postgres
    {
      label: "GPS to Postgres",
      type: "hld",
      href: "/saas/vistabeam/gps_db",
      desc_en: "Import new graded GPS survey, or append to existing tables.",
      desc_fr: "Importe nouveau relevé GPS calibré, ou ajoute à existant.",
      version: "1.0.0",
      date_upd: "2024-01-25",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "Y",
    },
    // GPS Postgres - Override
    {
      label: "GPS to Postgres",
      type: "override",
      href: "/saas/vistabeam/override_gps",
      desc_en: "Fresh GPS import, erasing old data.",
      desc_fr: "Nouvel import GPS, effaçant anciennes données.",
      version: "1.0.0",
      date_upd: "2024-01-25",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "Y",
    },
    // Poles table pre-fill and suggestions calculation - by Node
    {
      label: "Node Poles Calculations",
      type: "hld",
      href: "/saas/vistabeam/node_poles_calc",
      desc_en: "Poles attachment suggestions and table pre-fill, by Node.",
      desc_fr:
        "Suggestions hauteurs d'attaches poteaux, et pre-remplissage tableaux, par noeud.",
      version: "1.0.0",
      date_upd: "2024-01-23",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "doc_dfn_poles_calculator",
      is_active: "Y",
    },
    // SUPER APPS
    // Resolve Null Geom
    {
      label: "Resolve Null Geom",
      type: "super",
      href: "/saas/vistabeam/super_resolve_null_geom",
      desc_en: "Postgres db remove Null geometries.",
      desc_fr: "Postgres db supprime les géometries Null.",
      version: "1.0.0",
      date_upd: "2024-01-23",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "Y",
    },
    // Recover deleted data
    {
      label: "Recover from Version",
      type: "super",
      href: "/saas/vistabeam/super_recover_version",
      desc_en: "Postgres db recover deleted data, from versioning.",
      desc_fr: "Postgres db restaure data supprimées, depuis versioning.",
      version: "1.0.0",
      date_upd: "2024-01-23",
      desc_upd_en: "Vistabeam tools implementation.",
      desc_upd_fr: "Implémentation des outils Vistabeam.",
      doc_href: "empty",
      is_active: "Y",
    },
  ],
};
