import { StyleSheet } from "@react-pdf/renderer";

export const StylesPDF = StyleSheet.create({
  page: {
    position: "relative",
    flexDirection: "column",
    padding: "50 80",
    fontSize: 12,
    lineHeight: 1,
    fontFamily: "Helvetica",
  },
  frontCoverSection: {
    top: 100,
    textAlign: "center",
    fontFamily: "Helvetica-Bold",
  },
  frontCoverCredits: {
    position: "absolute",
    bottom: 50,
    left: 50,
    right: 50,
    textAlign: "justify",
    fontSize: 10,
    color: "#ACC6FC",
    paddingLeft: 40,
    paddingRight: 40,
  },
  frontCoverImage: {
    paddingTop: 120,
    alignSelf: "center",
    width: "50%",
    height: "auto",
  },
  text: {
    marginBottom: 10,
  },
  imageContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    margin: 5,
  },
  image: {
    marginBottom: 3,
  },
  label: {
    textAlign: "center",
    fontSize: 10,
    fontFamily: "Helvetica-Oblique",
  },
  imageColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flexGrow: 1,
  },
  pageCount: {
    position: "absolute",
    bottom: 10,
    left: 10,
    right: 0,
    textAlign: "left",
    fontSize: 10,
  },
  pageImageFooter: {
    position: "absolute",
    bottom: -1,
    right: -2,
    width: 50,
    height: 50,
  },
  pageClientLogo: {
    position: "absolute",
    top: 30,
    right: 20,
    height: "auto",
    width: 120,
  },
  pageTDLogo: {
    position: "absolute",
    top: 20,
    left: 20,
    height: 40,
    width: "auto",
  },
  sectionTitleContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  sectionAuthorContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    lineHeight: 1.5,
  },
  pageTitle: {
    fontSize: 14,
    paddingBottom: 30,
    textTransform: "uppercase",
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    textDecoration: "underline",
  },
  PageContentSection: {
    lineHeight: 1.2,
    textAlign: "justify",
    paddingBottom: 10,
  },
  PageNotesContentSection: {
    lineHeight: 0.8,
    textAlign: "justify",
    paddingBottom: 10,
  },
  PageContentSectionIndent: {
    textIndent: 20,
    lineHeight: 1.2,
    textAlign: "justify",
    paddingBottom: 10,
  },
  AppendixContentSection: {
    lineHeight: 1.2,
    fontSize: 10,
    textAlign: "justify",
    paddingBottom: 10,
  },
  AppendixContentSectionIndent: {
    textIndent: 20,
    fontSize: 10,
    lineHeight: 1.2,
    textAlign: "justify",
    paddingBottom: 10,
  },
  listItemContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingLeft: 20,
    marginBottom: 5,
    fontSize: 10,
  },
  subListItemContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingLeft: 20,
    marginBottom: 5,
  },
  listTitle: {
    fontSize: 11,
    textDecoration: "underline",
    paddingBottom: 5,
  },
  listTitleBold: {
    fontSize: 11,
    textDecoration: "underline",
    fontFamily: "Helvetica-Bold",
    paddingBottom: 5,
  },
  listItemNumber: {
    width: 20,
  },
  listItemText: {
    flex: 1,
    textAlign: "justify",
  },
  sideBySideContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sideBySideItem: {
    width: "50%",
  },
  tableContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 15,
  },
  thContainerA: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    border: "1 solid #000",
    alignItems: "center",
    fontSize: 10,
    textAlign: "center",
    fontFamily: "Helvetica-Bold",
    flexGrow: 1,
  },
  thElevation: {
    width: "10%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thAntenna: {
    width: "30%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thAzimuth: {
    width: "8%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thTxLine: {
    width: "19%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thOdu: {
    width: "23%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thCarrier: {
    padding: "5px 0",
    width: "10%",
  },
  trContainerA: {
    flexDirection: "row",
    borderBottomColor: "#000",
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    fontSize: 10,
    textAlign: "center",
    alignItems: "stretch",
  },
  trElevation: {
    width: "10%",
    padding: "2px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trAntenna: {
    width: "30%",
    padding: "2px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trAzimuth: {
    width: "8%",
    padding: "2px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trTxLine: {
    width: "19%",
    padding: "2px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trOdu: {
    width: "23%",
    padding: "2px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trCarrier: {
    padding: "2px 0",
    width: "10%",
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  thContainerD: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    border: "1 solid #000",
    alignItems: "center",
    fontSize: 10,
    textAlign: "center",
    fontFamily: "Helvetica-Bold",
    flexGrow: 1,
  },
  thItemNb: {
    width: "10%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thProcedure: {
    width: "25%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thDeficiency: {
    width: "25%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thRecommendation: {
    width: "25%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thPhoto: {
    width: "15%",
    padding: "5px 0",
  },
  trContainerD: {
    flexDirection: "row",
    borderBottomColor: "#000",
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    fontSize: 10,
    textAlign: "center",
    alignItems: "stretch",
  },
  trItemNb: {
    width: "10%",
    padding: "2px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trProcedure: {
    width: "25%",
    padding: "2px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trDeficiency: {
    width: "25%",
    padding: "2px",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trRecommendation: {
    width: "25%",
    padding: "2px",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trPhoto: {
    padding: "2px 0",
    width: "15%",
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  // new
  thContainerCTitle: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: "#000",
    alignItems: "center",
    fontSize: 9,
    textAlign: "left",
    fontFamily: "Helvetica-Bold",
    flexGrow: 1,
  },
  thTopTitle: {
    width: "100%",
    padding: 5,
    fontSize: 10,
  },
  thContainerC: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    border: "1 solid #000",
    alignItems: "center",
    fontSize: 9,
    textAlign: "center",
    fontFamily: "Helvetica-Bold",
    flexGrow: 1,
  },
  thCode: {
    width: "10%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thItem: {
    width: "40%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thYes: {
    width: "5%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thNo: {
    width: "5%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thNA: {
    width: "5%",
    padding: "5px 0",
    borderRightColor: "#000",
    borderRightWidth: 1,
  },
  thComments: {
    width: "35%",
    padding: "5px 0",
  },
  trContainerC: {
    flexDirection: "row",
    borderBottomColor: "#000",
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    fontSize: 9,
    textAlign: "center",
    alignItems: "stretch",
  },
  trCode: {
    width: "10%",
    padding: "2px",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trItem: {
    width: "40%",
    padding: "2px",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    textAlign: "left",
    display: "flex",
  },
  trYes: {
    width: "5%",
    padding: "2px",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trNo: {
    width: "5%",
    padding: "2px",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trNA: {
    width: "5%",
    padding: "2px",
    borderRightColor: "#000",
    borderRightWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  trComments: {
    width: "35%",
    padding: "2px",
    justifyContent: "center",
    textAlign: "left",
    display: "flex",
  },
});
