name: Assign New Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to creator
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;
            const assignees = [context.actor];

            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number,
              assignees
            });
