name: Update README Tags on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Montreal'  # Set timezone to Eastern Time

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README badges
        run: |
          # Read version from package.json
          VERSION=$(node -p "require('./package.json').version")
          # Format date to YYYY-MM-DD
          DATE_UPDATED=$(date +'%Y-%m-%d')
          sed -i "s/version-[^)]*/version-${VERSION}-blue/g" README.md
          sed -i "s/last%20updated-[^)]*/last%20updated-${DATE_UPDATED}-brightgreen/g" README.md

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config pull.rebase true

      - name: Check and commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add README.md
            git commit -m 'Update version and last updated badges in README'
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi
